services:
  api_server:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - PORT=8000
    ports:
      - 8000:8000
    volumes:
      - ./file:/app/file
  test_session:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: mocha src/tests/index.js
